SHELL := /bin/bash

## Inherit targets from another Makefile
%:
	make -f ../../shared/makefiles/SLSMakefile $@

## CI TARGETS

build-module:
	echo "No lib build defined for this sls module"

# DEVELOPER TARGETS
# Developers can add custom targets below at will

