#!/bin/bash

rm -f ./static/_config.js 

echo "// Autogenerated file" >> ./static/_config.js

# Find all the CONFIG_ environment variables in the environment
declare -a customVars
for key in $(env | awk -F "=" '{print $1}' | grep ".*CONFIG_.*")
do
  customVars+=($key)
done

# Add variables to config.js
for key in "${customVars[@]}"
do
  echo "window.$key='${!key}';" >> ./static/_config.js
done

